

javascript: var v = document.getElementsByTagName("video")[0].src;
document.body.innerHTML = `<video src="${v}"></video>`+ document.body.innerHTML;



var listt = `	https://www.startwithunitec.com/helper-scripts
https://www.startwithunitec.com/template
https://www.startwithunitec.com/Credit-Card-Setup-Applications
https://www.startwithunitec.com/Sentinel
https://www.startwithunitec.com/Portal-TI
https://www.startwithunitec.com/Priority-Payments-Application
https://www.startwithunitec.com/home-slider-order
https://www.startwithunitec.com/slider-banner-0
https://www.startwithunitec.com/Coronavirus-Resources
https://www.startwithunitec.com/Trade-Show-Schedule
https://www.startwithunitec.com/ContactUs
https://www.startwithunitec.com/Whats-New
https://www.startwithunitec.com/Technical-Support-testpage
https://www.startwithunitec.com/Repair-Request-Form
https://www.startwithunitec.com/operatorsupport
https://www.startwithunitec.com/How-to-Add-Users-to-a-Fleet-Account-Add-User-to-Fleet-Account
https://www.startwithunitec.com/How-to-Setup-a-Fleet-Account-Setup-Fleet-Account
https://www.startwithunitec.com/operatorsupport30dayterms
https://www.startwithunitec.com/Credit-Card-Compatibility-Chart
https://www.startwithunitec.com/4-Seasons-of-Carwash-Marketing
https://www.startwithunitec.com/C-Start
https://www.startwithunitec.com/uptime
https://www.startwithunitec.com/Pay-Station-Security
https://www.startwithunitec.com/How-to-Setup-a-Pre-Paid-Account-Setup-Sales-Buttons
https://www.startwithunitec.com/Register-Your-Product
https://www.startwithunitec.com/C-Start-Canada
https://www.startwithunitec.com/Locations
https://www.startwithunitec.com/Back-To-Basics
https://www.startwithunitec.com/How-to-Backup-a-Database-Manually-Backup-Database
https://www.startwithunitec.com/How-to-Login-to-the-Sierra-Management-System
https://www.startwithunitec.com/How-to-Backup-a-Database-Enable-Automatic-Backups
https://www.startwithunitec.com/The-Hidden-Factor
https://www.startwithunitec.com/mobiletemplate2019
https://www.startwithunitec.com/Human-form-test
https://www.startwithunitec.com/slider-banner-4
https://www.startwithunitec.com/home
https://www.startwithunitec.com/Uptime-Solutions-Press-Release
https://www.startwithunitec.com/Wash-Select-II
https://www.startwithunitec.com/Thank-You
https://www.startwithunitec.com/home-beta
https://www.startwithunitec.com/PCI-and-EMV
https://www.startwithunitec.com/PCI-Compliance
https://www.startwithunitec.com/slider-banner-3
https://www.startwithunitec.com/slider-banner-2
https://www.startwithunitec.com/slider-banner-1
https://www.startwithunitec.com/Protecting-your-Car-Wash-in-Severe-Weather
https://www.startwithunitec.com/FormTestPage-1560876803
https://www.startwithunitec.com/pricing-access-request
https://www.startwithunitec.com/Sentinel-How-To-Guides
https://www.startwithunitec.com/Portal-TI-How-To-Guides
https://www.startwithunitec.com/How-to-Setup-a-Multi-Wash-Package
https://www.startwithunitec.com/C-Start-How-To-Guides
https://www.startwithunitec.com/training-template-shell
https://www.startwithunitec.com/4-Creative-Marketing-Ideas
https://www.startwithunitec.com/3-Trends-Impacting-Carwash-POS
https://www.startwithunitec.com/Online-Training-Overview
https://www.startwithunitec.com/the-car-wash-show-2019
https://www.startwithunitec.com/WashPay-Current
https://www.startwithunitec.com/WashPay-Legacy
https://www.startwithunitec.com/Sentinel-CF
https://www.startwithunitec.com/Portal-Touch-CF
https://www.startwithunitec.com/Portal-CF
https://www.startwithunitec.com/Site-Management
https://www.startwithunitec.com/WashPay
https://www.startwithunitec.com/Install-by-Department
https://www.startwithunitec.com/Edit-the-Product
https://www.startwithunitec.com/Edit-a-User-Profile
https://www.startwithunitec.com/Download-Device-Profile
https://www.startwithunitec.com/Download-All-Devices
https://www.startwithunitec.com/Configure-Wash-Dispensing
https://www.startwithunitec.com/Configure-Added-Services-Dispensing
https://www.startwithunitec.com/Association-Logos
https://www.startwithunitec.com/Add-New-Wash-Type
https://www.startwithunitec.com/Kathy-Hofstad-Biography
https://www.startwithunitec.com/Multi-Site
https://www.startwithunitec.com/test-page
https://www.startwithunitec.com/FormTestPage-1545053874
https://www.startwithunitec.com/Complementary-Products
https://www.startwithunitec.com/Director
https://www.startwithunitec.com/home-sentinel
https://www.startwithunitec.com/Sentinel-test
https://www.startwithunitec.com/verifone
https://www.startwithunitec.com/unitec-production-notes-for-hank
https://www.startwithunitec.com/test
https://www.startwithunitec.com/test-home-august-8-2017lr
https://www.startwithunitec.com/test-home-august-8-2017
https://www.startwithunitec.com/test-home-august-8-2017-RGB-color-banner
https://www.startwithunitec.com/test-b27
https://www.startwithunitec.com/test-b26
https://www.startwithunitec.com/template2017
https://www.startwithunitec.com/template2017-beta
https://www.startwithunitec.com/template2017-beta-hank
https://www.startwithunitec.com/template2017-BU-2017-5-8
https://www.startwithunitec.com/template2016
https://www.startwithunitec.com/template2016-utf8
https://www.startwithunitec.com/slick-widget-test
https://www.startwithunitec.com/Wi-Fi-Bridge
https://www.startwithunitec.com/Whats-New-edits
https://www.startwithunitec.com/West-Coast-Press-Release
https://www.startwithunitec.com/West-Coast-Opens-Press-Release
https://www.startwithunitec.com/Website-ECommerce-Launch
https://www.startwithunitec.com/Web-hosting-discussion
https://www.startwithunitec.com/WashSelectII-Photos
https://www.startwithunitec.com/WashSelectII-Manuals
https://www.startwithunitec.com/WashSelectII-How-To-Guides
https://www.startwithunitec.com/WashSelectII-Browse-Parts
https://www.startwithunitec.com/WashSelectII-Ancillary-Products
https://www.startwithunitec.com/WashPay-Photos
https://www.startwithunitec.com/WashPay-Manuals
https://www.startwithunitec.com/WashPay-Landing
https://www.startwithunitec.com/WashPay-How-To-Guides
https://www.startwithunitec.com/WashPay-Browse-Parts
https://www.startwithunitec.com/WashPay-Ancillary-Products
https://www.startwithunitec.com/Wash-Select-II-Video
https://www.startwithunitec.com/Wash-Select-II-How-To-Guides
https://www.startwithunitec.com/Wash-Select-II-Ancillary-Products
https://www.startwithunitec.com/WarrantyApril2015
https://www.startwithunitec.com/Warranty
https://www.startwithunitec.com/WSII-promo-beta
https://www.startwithunitec.com/WSII-Enhanced-Heater
https://www.startwithunitec.com/Video-Embed-example
https://www.startwithunitec.com/User-Agreement
https://www.startwithunitec.com/Upgrade
https://www.startwithunitec.com/Untitled-Document-2018-02-09-14-45-06
https://www.startwithunitec.com/Training
https://www.startwithunitec.com/Training-access-request
https://www.startwithunitec.com/Training-access-request-response
https://www.startwithunitec.com/Training-Intro-Text
https://www.startwithunitec.com/Trade-Show-Schedule-gray-rows
https://www.startwithunitec.com/Trade-Show-Schedule-beta
https://www.startwithunitec.com/Trade-Show-Schedule-No-Fader
https://www.startwithunitec.com/Trade-Show-Schedule-Fader
https://www.startwithunitec.com/The-Car-Wash-Show-2018
https://www.startwithunitec.com/Technical-Support
https://www.startwithunitec.com/Technical-Support-Beta
https://www.startwithunitec.com/Table-Help-Template
https://www.startwithunitec.com/TMD-demo
https://www.startwithunitec.com/Subscription-Account-How-To
https://www.startwithunitec.com/Start-Here
https://www.startwithunitec.com/Slideshow-Example
https://www.startwithunitec.com/Site-Operators
https://www.startwithunitec.com/Site-Map
https://www.startwithunitec.com/Site-Management-Photos
https://www.startwithunitec.com/Site-Management-Manuals
https://www.startwithunitec.com/Site-Management-How-To-Guides
https://www.startwithunitec.com/Site-Management-Browse-Parts
https://www.startwithunitec.com/Site-Management-Ancillary-Products
https://www.startwithunitec.com/Silvercrayon-Help-Videos
https://www.startwithunitec.com/Sierra-Site-Controller-Photos
https://www.startwithunitec.com/Sierra-Site-Controller-Manuals
https://www.startwithunitec.com/Sierra-Site-Controller-How-To-Guides
https://www.startwithunitec.com/Sierra-Site-Controller-Browse-Parts
https://www.startwithunitec.com/Sierra-Site-Controller-Ancillary-Products
https://www.startwithunitec.com/Setup-Prepaid-Account-Program
https://www.startwithunitec.com/Sentinel-SSD
https://www.startwithunitec.com/Sentinel-Photos
https://www.startwithunitec.com/Sentinel-Manuals
https://www.startwithunitec.com/Sentinel-Landing
https://www.startwithunitec.com/Sentinel-Browse-Parts
https://www.startwithunitec.com/Sentinel-Ancillary-Products
https://www.startwithunitec.com/Self-Paced-Courses
https://www.startwithunitec.com/Self-Paced-Courses-design-mockup
https://www.startwithunitec.com/searchtemplate
https://www.startwithunitec.com/right-widget-from-2015
https://www.startwithunitec.com/related-products-beta
https://www.startwithunitec.com/redirect-test
https://www.startwithunitec.com/onlinetraining
https://www.startwithunitec.com/offline
https://www.startwithunitec.com/no-underline
https://www.startwithunitec.com/news-subscribe
https://www.startwithunitec.com/mobiletemplate2016
https://www.startwithunitec.com/mobiletemplate2016-bu
https://www.startwithunitec.com/marketing-form-response
https://www.startwithunitec.com/htest
https://www.startwithunitec.com/how-to-set-up-token-dispensing
https://www.startwithunitec.com/how-to-set-up-a-free-wash
https://www.startwithunitec.com/homeoct18
https://www.startwithunitec.com/homeBU
https://www.startwithunitec.com/home.txt
https://www.startwithunitec.com/home-test-december-2016
https://www.startwithunitec.com/home-test-december-2016-hank
https://www.startwithunitec.com/home-september
https://www.startwithunitec.com/home-sept28test
https://www.startwithunitec.com/home-mobile
https://www.startwithunitec.com/home-mobile-test
https://www.startwithunitec.com/home-mobile-recovered
https://www.startwithunitec.com/home-march2017
https://www.startwithunitec.com/home-june2017v2
https://www.startwithunitec.com/home-june2017
https://www.startwithunitec.com/home-backupMarch172017
https://www.startwithunitec.com/home-b26
https://www.startwithunitec.com/home-august3
https://www.startwithunitec.com/home-august2
https://www.startwithunitec.com/home-august
https://www.startwithunitec.com/home-august-IE-fix
https://www.startwithunitec.com/home-archiveSept182017
https://www.startwithunitec.com/home-Sept172017
https://www.startwithunitec.com/home-Oct2017
https://www.startwithunitec.com/home-Nov22017
https://www.startwithunitec.com/home-Junev3
https://www.startwithunitec.com/home-Aug-changes
https://www.startwithunitec.com/home-Aug-changes-recovered
https://www.startwithunitec.com/home-767
https://www.startwithunitec.com/home-2016
https://www.startwithunitec.com/home-11102017
https://www.startwithunitec.com/home-103117
https://www.startwithunitec.com/hank-test
https://www.startwithunitec.com/hank-test-23
https://www.startwithunitec.com/hank-homepage-test-june-12
https://www.startwithunitec.com/front-page-banner
https://www.startwithunitec.com/form-data-viewer
https://www.startwithunitec.com/financing
https://www.startwithunitec.com/financing-beta
https://www.startwithunitec.com/expo-west-2018
https://www.startwithunitec.com/email-focus-group
https://www.startwithunitec.com/custom-search
https://www.startwithunitec.com/craft27
https://www.startwithunitec.com/contactline
https://www.startwithunitec.com/contact
https://www.startwithunitec.com/careers
https://www.startwithunitec.com/careers-june
https://www.startwithunitec.com/careers-beta
https://www.startwithunitec.com/cWashPal
https://www.startwithunitec.com/cWashPal-Photos
https://www.startwithunitec.com/cWashPal-Manuals
https://www.startwithunitec.com/cWashPal-How-To-Guides
https://www.startwithunitec.com/cWashPal-Browse-Parts
https://www.startwithunitec.com/cWashPal-Ancillary-Products
https://www.startwithunitec.com/c-start-ancillary-products
https://www.startwithunitec.com/button-styles-used
https://www.startwithunitec.com/button-styles-for-jen
https://www.startwithunitec.com/button-copier
https://www.startwithunitec.com/beta
https://www.startwithunitec.com/beta-test-page
https://www.startwithunitec.com/all-SRCs-listed-1004
https://www.startwithunitec.com/alert-monitoring
https://www.startwithunitec.com/about
https://www.startwithunitec.com/Self-Paced-Courses-December-1
https://www.startwithunitec.com/Return-Request-Form
https://www.startwithunitec.com/ReachFree-ID
https://www.startwithunitec.com/ReachFree-ID-Photos
https://www.startwithunitec.com/ReachFree-ID-Manuals
https://www.startwithunitec.com/ReachFree-ID-How-To-Guides
https://www.startwithunitec.com/ReachFree-ID-Browse-Parts
https://www.startwithunitec.com/ReachFree-ID-Ancillary-Products
https://www.startwithunitec.com/Programming-the-Coin-Dispenser
https://www.startwithunitec.com/Product-Timeline
https://www.startwithunitec.com/Product-List-Simple
https://www.startwithunitec.com/Product-Bulletin-Multimech-beta
https://www.startwithunitec.com/Privacy-Policy
https://www.startwithunitec.com/Priority-Payments-beta
https://www.startwithunitec.com/Priority-Payment-Testimonials
https://www.startwithunitec.com/Portal-Touch
https://www.startwithunitec.com/Portal-Touch-SSD
https://www.startwithunitec.com/Portal-Touch-HM
https://www.startwithunitec.com/Portal-TI-Photos
https://www.startwithunitec.com/Portal-TI-Manuals
https://www.startwithunitec.com/Portal-TI-Browse-Parts
https://www.startwithunitec.com/Portal-TI-Ancillary-Products
https://www.startwithunitec.com/Portal-SSD
https://www.startwithunitec.com/Portal-Landing
https://www.startwithunitec.com/Portal-Keypad
https://www.startwithunitec.com/Portal-CF-hm
https://www.startwithunitec.com/Portal-CF-beta
https://www.startwithunitec.com/Past-Home-page-Designs
https://www.startwithunitec.com/Parts-and-Accessories-Return-Policy
https://www.startwithunitec.com/Pam-Piro-Biography
https://www.startwithunitec.com/POS-Test
https://www.startwithunitec.com/Operating-System-Updates
https://www.startwithunitec.com/Operating-System-Updates-hank
https://www.startwithunitec.com/Operating-System-Updates-beta
https://www.startwithunitec.com/October-12
https://www.startwithunitec.com/Notes-from-september-8
https://www.startwithunitec.com/Notes-from-september-30
https://www.startwithunitec.com/Notes-from-september-15
https://www.startwithunitec.com/Notes-from-October-8
https://www.startwithunitec.com/Notes-from-October-5
https://www.startwithunitec.com/Notes-from-October-4-2016
https://www.startwithunitec.com/Notes-from-December-2-2015
https://www.startwithunitec.com/New-Wash-Product-Setup
https://www.startwithunitec.com/MultiMech-Bill-Dispenser
https://www.startwithunitec.com/MultiMech-Bill-Dispenser-Update
https://www.startwithunitec.com/Multi-Site-Photos
https://www.startwithunitec.com/Multi-Site-Manuals
https://www.startwithunitec.com/Multi-Site-How-To-Guides
https://www.startwithunitec.com/Multi-Site-Browse-Parts
https://www.startwithunitec.com/Multi-Site-Ancillary-Products
https://www.startwithunitec.com/Monthly-Billing-Statement-for-Fleet-Customers
https://www.startwithunitec.com/Monthly-Billing-Statement-for-Fleet-Customers-Send-Fleet-Report
https://www.startwithunitec.com/Monthly-Billing-Statement-for-Fleet-Customers-Enter-Fleet-Report-Parameters
https://www.startwithunitec.com/Michael-White-Biography
https://www.startwithunitec.com/Marketing-Your-Carwash
https://www.startwithunitec.com/Marketing-Your-Carwash-Long
https://www.startwithunitec.com/Marketing-Your-Carwash-Content
https://www.startwithunitec.com/Marketing-Tools
https://www.startwithunitec.com/Marketing-Tools-Photos
https://www.startwithunitec.com/Marketing-Tools-Manuals
https://www.startwithunitec.com/Marketing-Tools-How-To-Guides
https://www.startwithunitec.com/Marketing-Tools-Browse-Parts
https://www.startwithunitec.com/Marketing-Tools-Ancillary-Products
https://www.startwithunitec.com/Manuals
https://www.startwithunitec.com/Manual-search-aid-hank
https://www.startwithunitec.com/Management-Team
https://www.startwithunitec.com/MFA
https://www.startwithunitec.com/MCBIN-Security-Changestest
https://www.startwithunitec.com/MCBIN-Security-Changes
https://www.startwithunitec.com/MCBIN-Register-System
https://www.startwithunitec.com/MCBIN-Overview
https://www.startwithunitec.com/MCBIN-Modemtest
https://www.startwithunitec.com/MCBIN-Modem
https://www.startwithunitec.com/MCBIN-Credit-Processor
https://www.startwithunitec.com/Line-Conditioner
https://www.startwithunitec.com/Keynote2017
https://www.startwithunitec.com/International
https://www.startwithunitec.com/Instructional-Videos
https://www.startwithunitec.com/Installation-by-Appointment
https://www.startwithunitec.com/Inside-Sales
https://www.startwithunitec.com/Industry-Changes-Overview
https://www.startwithunitec.com/IDs-with-iframes
https://www.startwithunitec.com/How-to-Setup-a-Subscription-Account
https://www.startwithunitec.com/How-to-Setup-a-Scheduled-Special
https://www.startwithunitec.com/How-to-Setup-a-Scheduled-Special-Setup-Special-in-Promotions
https://www.startwithunitec.com/How-to-Setup-a-Pre-Paid-Account
https://www.startwithunitec.com/How-to-Setup-a-Pre-Paid-Account-Setup-Pre-paid-Account-Program
https://www.startwithunitec.com/How-to-Setup-a-Pre-Paid-Account-Purchase-Account-on-Sales-Screen
https://www.startwithunitec.com/How-to-Setup-a-New-Added-Service
https://www.startwithunitec.com/How-to-Setup-a-Loyalty-Account
https://www.startwithunitec.com/How-to-Setup-a-Loyalty-Account-Setup-Sales-Button
https://www.startwithunitec.com/How-to-Setup-a-Loyalty-Account-Setup-Loyalty-Account-Program
https://www.startwithunitec.com/How-to-Setup-a-Loyalty-Account-Purchase-Account-on-Sales-Screen
https://www.startwithunitec.com/How-to-Setup-a-Hidden-Wash-Package
https://www.startwithunitec.com/How-to-Setup-a-Fundraiser
https://www.startwithunitec.com/How-to-Setup-a-Fundraiser-Setup-Fundraiser-in-Promotions
https://www.startwithunitec.com/How-to-Setup-a-Free-Wash
https://www.startwithunitec.com/How-to-Setup-a-Fleet-Account
https://www.startwithunitec.com/How-to-Setup-Notifications
https://www.startwithunitec.com/How-to-Setup-Notifications-Setup-Notifications
https://www.startwithunitec.com/How-to-Setup-Loyalty-Account
https://www.startwithunitec.com/How-to-Setup-Discounts
https://www.startwithunitec.com/How-to-Setup-Discounts-Setup-Discount-in-Promotions
https://www.startwithunitec.com/How-to-Setup-Discounts-Download-All-Devices
https://www.startwithunitec.com/How-to-Setup-Buttons-for-the-Console-Screen-Setup-Sales-Buttons
https://www.startwithunitec.com/How-to-Restore-a-Database-Restore-from-Database-Backup
https://www.startwithunitec.com/How-to-Change-Wash-Details
https://www.startwithunitec.com/How-to-Change-Prices
https://www.startwithunitec.com/How-to-Backup-a-Database
https://www.startwithunitec.com/How-to-Add-or-Delete-User
https://www.startwithunitec.com/How-to-Add-or-Delete-User-Edit-a-User-Profile
https://www.startwithunitec.com/How-to-Add-Account-Product
https://www.startwithunitec.com/How-To-Guides
https://www.startwithunitec.com/How-To-Guides-How-to-Setup-a-New-Wash-Type
https://www.startwithunitec.com/How-To-Guides-How-to-Restore-a-Database
https://www.startwithunitec.com/History
https://www.startwithunitec.com/Help
https://www.startwithunitec.com/HTT
https://www.startwithunitec.com/HMT
https://www.startwithunitec.com/Guides
https://www.startwithunitec.com/Gilbarco-Passport
https://www.startwithunitec.com/Frequently-Asked-Questions-FAQs
https://www.startwithunitec.com/Frequently-Asked-Questions-FAQs-beta
https://www.startwithunitec.com/FormTestPage-1536247227
https://www.startwithunitec.com/FormTestPage-1527689308
https://www.startwithunitec.com/FormTestPage-1504713099
https://www.startwithunitec.com/FormTestPage-1465838003
https://www.startwithunitec.com/FormTestPage-1465829986
https://www.startwithunitec.com/FormTestPage-1462644744
https://www.startwithunitec.com/Financing-Press-Release
https://www.startwithunitec.com/Ethernet-Extender-Wi-Fi-Bridge
https://www.startwithunitec.com/EZ-Trak
https://www.startwithunitec.com/EZ-Trak-Photos
https://www.startwithunitec.com/EZ-Trak-Manuals
https://www.startwithunitec.com/EZ-Trak-How-To-Guides
https://www.startwithunitec.com/EZ-Trak-Browse-Parts
https://www.startwithunitec.com/EZ-Trak-Ancillary-Products
https://www.startwithunitec.com/EMV-Update-November-2015
https://www.startwithunitec.com/EMV-Update-June-2016
https://www.startwithunitec.com/Distributors
https://www.startwithunitec.com/Distributors-oct-12-2015
https://www.startwithunitec.com/Distributor
https://www.startwithunitec.com/Director-test
https://www.startwithunitec.com/Director-beta
https://www.startwithunitec.com/Director-archive-May-2018
https://www.startwithunitec.com/Director-Oct2017
https://www.startwithunitec.com/Director-Oct2017-HM
https://www.startwithunitec.com/Director-Copy
https://www.startwithunitec.com/DRB-Unitec-Press-Release
https://www.startwithunitec.com/Customer-Service
https://www.startwithunitec.com/Customer-Service-beta
https://www.startwithunitec.com/Custom-Overlay
https://www.startwithunitec.com/Custom-Overlay-beta
https://www.startwithunitec.com/Custom-Overlay-beta-HM
https://www.startwithunitec.com/Custom-Overlay-beta-HM-v002
https://www.startwithunitec.com/Credit-Card-Set-Up
https://www.startwithunitec.com/Credit-Card-Set-Up-August
https://www.startwithunitec.com/Credit-Card-Compatibility-Chart-beta
https://www.startwithunitec.com/Credit-Card-Compatibility-Chart-Aug2017
https://www.startwithunitec.com/Convenience-Stores
https://www.startwithunitec.com/ContactUs-recovered-by-hank
https://www.startwithunitec.com/ContactUs-brad
https://www.startwithunitec.com/ContactUs-beta
https://www.startwithunitec.com/Complimentary-Products
https://www.startwithunitec.com/Complementary-Products-beta
https://www.startwithunitec.com/Calendars-for-2015-and-2016
https://www.startwithunitec.com/Calendar-of-Events
https://www.startwithunitec.com/Calendar-of-Events-September-2015
https://www.startwithunitec.com/Calendar-of-Events-October-2015
https://www.startwithunitec.com/Calendar-of-Events-November-2015
https://www.startwithunitec.com/Calendar-of-Events-May-2016
https://www.startwithunitec.com/Calendar-of-Events-March-2016
https://www.startwithunitec.com/Calendar-of-Events-January-2016
https://www.startwithunitec.com/Calendar-of-Events-February-2016
https://www.startwithunitec.com/Calendar-of-Events-December-2015
https://www.startwithunitec.com/Calendar-of-Events-April-2016
https://www.startwithunitec.com/CStart-Landing
https://www.startwithunitec.com/C-Start-Photos
https://www.startwithunitec.com/C-Start-Manuals
https://www.startwithunitec.com/C-Start-Browse-Parts
https://www.startwithunitec.com/Brenda-Budzynski-Biography
https://www.startwithunitec.com/Blue-button-style
https://www.startwithunitec.com/Ancillary-Products-pastebin
https://www.startwithunitec.com/About-Unitec
https://www.startwithunitec.com/404
https://www.startwithunitec.com/404-recovered
https://www.startwithunitec.com/404-newtest
https://www.startwithunitec.com/3-cards`;
var out = ``;
var l = listt.split(`\n`);
console.log(l);
for (var i = 0; i < l.length; i++) {
    if (l[i].match(/how\-to/ig)) {
        out += `${l[i]}<br>`;
    }
}
document.body.innerHTML = out;


var howtos = `https://www.startwithunitec.com/How-to-Add-Users-to-a-Fleet-Account-Add-User-to-Fleet-Account
https://www.startwithunitec.com/How-to-Setup-a-Fleet-Account-Setup-Fleet-Account
https://www.startwithunitec.com/How-to-Setup-a-Pre-Paid-Account-Setup-Sales-Buttons
https://www.startwithunitec.com/How-to-Backup-a-Database-Manually-Backup-Database
https://www.startwithunitec.com/How-to-Login-to-the-Sierra-Management-System
https://www.startwithunitec.com/How-to-Backup-a-Database-Enable-Automatic-Backups
https://www.startwithunitec.com/Sentinel-How-To-Guides
https://www.startwithunitec.com/Portal-TI-How-To-Guides
https://www.startwithunitec.com/How-to-Setup-a-Multi-Wash-Package
https://www.startwithunitec.com/C-Start-How-To-Guides
https://www.startwithunitec.com/WashSelectII-How-To-Guides
https://www.startwithunitec.com/WashPay-How-To-Guides
https://www.startwithunitec.com/Wash-Select-II-How-To-Guides
https://www.startwithunitec.com/Subscription-Account-How-To
https://www.startwithunitec.com/Site-Management-How-To-Guides
https://www.startwithunitec.com/Sierra-Site-Controller-How-To-Guides
https://www.startwithunitec.com/how-to-set-up-token-dispensing
https://www.startwithunitec.com/how-to-set-up-a-free-wash
https://www.startwithunitec.com/cWashPal-How-To-Guides
https://www.startwithunitec.com/ReachFree-ID-How-To-Guides
https://www.startwithunitec.com/Multi-Site-How-To-Guides
https://www.startwithunitec.com/Marketing-Tools-How-To-Guides
https://www.startwithunitec.com/How-to-Setup-a-Subscription-Account
https://www.startwithunitec.com/How-to-Setup-a-Scheduled-Special
https://www.startwithunitec.com/How-to-Setup-a-Scheduled-Special-Setup-Special-in-Promotions
https://www.startwithunitec.com/How-to-Setup-a-Pre-Paid-Account
https://www.startwithunitec.com/How-to-Setup-a-Pre-Paid-Account-Setup-Pre-paid-Account-Program
https://www.startwithunitec.com/How-to-Setup-a-Pre-Paid-Account-Purchase-Account-on-Sales-Screen
https://www.startwithunitec.com/How-to-Setup-a-New-Added-Service
https://www.startwithunitec.com/How-to-Setup-a-Loyalty-Account
https://www.startwithunitec.com/How-to-Setup-a-Loyalty-Account-Setup-Sales-Button
https://www.startwithunitec.com/How-to-Setup-a-Loyalty-Account-Setup-Loyalty-Account-Program
https://www.startwithunitec.com/How-to-Setup-a-Loyalty-Account-Purchase-Account-on-Sales-Screen
https://www.startwithunitec.com/How-to-Setup-a-Hidden-Wash-Package
https://www.startwithunitec.com/How-to-Setup-a-Fundraiser
https://www.startwithunitec.com/How-to-Setup-a-Fundraiser-Setup-Fundraiser-in-Promotions
https://www.startwithunitec.com/How-to-Setup-a-Free-Wash
https://www.startwithunitec.com/How-to-Setup-a-Fleet-Account
https://www.startwithunitec.com/How-to-Setup-Notifications
https://www.startwithunitec.com/How-to-Setup-Notifications-Setup-Notifications
https://www.startwithunitec.com/How-to-Setup-Loyalty-Account
https://www.startwithunitec.com/How-to-Setup-Discounts
https://www.startwithunitec.com/How-to-Setup-Discounts-Setup-Discount-in-Promotions
https://www.startwithunitec.com/How-to-Setup-Discounts-Download-All-Devices
https://www.startwithunitec.com/How-to-Setup-Buttons-for-the-Console-Screen-Setup-Sales-Buttons
https://www.startwithunitec.com/How-to-Restore-a-Database-Restore-from-Database-Backup
https://www.startwithunitec.com/How-to-Change-Wash-Details
https://www.startwithunitec.com/How-to-Change-Prices
https://www.startwithunitec.com/How-to-Backup-a-Database
https://www.startwithunitec.com/How-to-Add-or-Delete-User
https://www.startwithunitec.com/How-to-Add-or-Delete-User-Edit-a-User-Profile
https://www.startwithunitec.com/How-to-Add-Account-Product
https://www.startwithunitec.com/How-To-Guides
https://www.startwithunitec.com/How-To-Guides-How-to-Setup-a-New-Wash-Type
https://www.startwithunitec.com/How-To-Guides-How-to-Restore-a-Database
https://www.startwithunitec.com/EZ-Trak-How-To-Guides`;



