pieletData.PNO = `<div>Your physiological needs are in pretty good shape. You seem to be taking good care of yourself regarding your general health and well-being, and there's always room for improvement.</div><div><br></div><div>A long and healthy life is within your reach, because you have a solid physiological foundation to work from. You'd be wise to work with a nutritionist and/or personal trainer, and start dialing in your nutrition and exercise regimen in to your specific needs, considering factors like your age, weight, BMI, and your own very specific health goals.</div><div><br></div><div>A key to maintaining, and growing your good physiological foundation is the company you keep. You'd do well to keep your distance from people that smoke, drink excessively, or are recreational drug users, as their lifestyles run counter to yours, and could hinder your progress towards an even healthier life.</div>`;
pieletData.SNO = `<div>You have a reasonable amount of certainty in your life regarding fundamental issues of safety and security, and that allows you to act from a spirit of abundance, rather than scarcity.</div> <div> <br></div> <div>This foundation of safety gives you a strong basis of emotional balance and personal fortitude, and makes you a rational actor in times when issues like housing security, food security, and personal safety might be in question. You know what safety and security in these areas look and feel like, thus you know that they are always attainable, even if life circumstances sometimes raise temporary doubts about them.</div> <div> <br></div> <div>Your core relationship to money is likely a healthy one, which is a key part of your foundation regarding the issues above. All the same, you might consider seeking the advice of a qualified financial advisor, or retirement specialists and developing a long-term plan to maintain and grow your financial assets over time. Doing so can alleviate some of the unspoken anxieties you might feel in these areas, freeing up your attention to apply to other important areas of your life.</div>`;
pieletData.LBO = `<div>Your relationship with yourself is a good one. You love yourself, and have compassion for yourself - and that's the root of love and compassion your able to show others.&nbsp;&nbsp;</div> <div> <br></div> <div>Authenticity is an important lever in the realm of love and belonging, and you probably show up pretty authentically in the groups and communities in which you operate. Continue this practice, and work to become ever more authentic, as it will increase you compassion for your fellow being and embed you even deeper into your community as a compassionate leader.&nbsp;&nbsp;</div> <div> <br></div> <div>Your love for yourself allows you a certain level of intimacy with yourself that not everyone has access too, and that level of personal intimacy transcends you and works its way into your personal relationships. People are okay being intimate with you, whether in conversation, or physically, because you're okay with intimacy. You radiate this in your words, actions and being - and people are attracted to you, because of it.&nbsp;&nbsp;</div> <div> <br></div> <div>Your foundation of love and belonging is a strong one, and with some additional nurturing, and perhaps some formal training, you could become a true force for compassion and healing in your world. You might consider taking some personal development courses, in order to increase your natural capacity for love and belonging.&nbsp;&nbsp;</div> <div> <br></div> <div>At the same time, be careful not to take on too much. Your natural strength in this area can be a beacon to people who feel deficient in this realm, drawing them to you as they seek your energy and love in order to compensate for their own lack of sense of love and belonging.</div> <div> <br></div> <div>Being present, powerful and compassionate towards others can in fact give you energy, but only when you have it to give. Make sure that your own needs in this area are well taken care of so you don't over-extend yourself and begin to feel drained by something that should give you joy.</div>`;
pieletData.ECO = `
<div>You have a strong, healthy self-esteem, and you're a contributor in this world - and there's an important relationship between the two.</div>
<div>
<br></div>
<div>Your ability to contribute to the world is likely based in your foundation of self-esteem, whereas some people's self-esteem is dependent on feeling that they make (or have made) and are recognized for their contributions. Good self-esteem, which is often rooted in positive childhood life experiences, allows us to be contributors to society as an end unto itself, not as a means to fill a perceived void within ourselves.</div>
<div>
<br></div>
<div>You may or may not have really come to understand, or embrace your purpose in life - but it's a great time to begin considering big questions like this, because defining, articulating, and sharing your purpose with others could result in your becoming a super-contributor.</div>
<div>
<br></div>
<div>Contributors affect change in society at the interpersonal level, and at the group level - and that's amazing in and of itself. Super-contributors affect the world at the community and at the meta level, and even the global level, and you're capable of that.</div>
<div>
<br></div>
<div>Studying from teachers, mentors, and coaches who are operating a level or two up from where you are currently affecting change would be of benefit to you if you're interested in operating at a higher level. Some personal development course work would also speed your trajectory towards those aims.&nbsp;</div>`;
pieletData.SAO = `<div>You seem to be aware that self actualization is a process - not a result, and you're consciously self-actualizing (seeking to be the best you that you can be) knowing well what effect that has on you, and others around you.</div>
<div>
<br></div>
<div>Your innate desire to be your most authentic self is an inspiration to so many people who may not have come to know, accept, or embrace themselves in the way in which you have. The world would benefit greatly from you working just as hard to express yourself to others, as you do to yourself.</div>
<div>
<br></div>
<div>Your gift is being you. Share yourself openly with the world, and lead by example. Shine your light as bright as you possibly can, and others will follow. You may light up the world someday, and you'll definitely light up a few faces, and light some minds on fire along the way.</div>
<div>
<br></div>
<div>Whatever you do - don't stop. Keep seeking knowledge, wisdom, and mentorship towards the things that are truly important to you - and share it openly.</div>
<div>
<br></div>
<div>Teaching is learning.`;
pieletData.PNU = `<p><font>You would benefit from eating better, getting more exercise, and a better night’s sleep.</font></p> 
<p><font>If you consume alcohol, caffeine, or use recreational drugs, these substances may be affecting your ability to sleep well at night, practice mindfulness (be in the moment) during your waking hours, and exercise the following day.&nbsp;</font></p> 
<p><font>Pay special attention to what you’re eating - and when, as the food you eat is providing you your base-level fuel to set and accomplish all of your other goals.</font></p> 
<p><font>Your community is key.&nbsp; Work to surround yourself with people that are healthier than you, as they’ll be a good influence on your actions.&nbsp;</font></p> 
<p><font>Depending on your specific circumstance you might consider working with a nutritionist, personal trainer, talk therapist, or addictions counselor if your actions regarding alcohol and/or drugs have ever caused harm to you or others, and you’ve continued to consume them.</font></p>`;
pieletData.SNU = `
<div>There’s a certain amount of (conscious or unconscious) uncertainty regarding your needs for fundamental safety and security.&nbsp; You may sometimes experience doubts in and around issues of sustainable access to housing, food security, and/or your personal safety. You may question your ability to deal with real or perceived shortfalls in these areas, and those doubts can affect your overall emotional stability and mental health.&nbsp;</div>
<div>
<br></div>
<div>Conversely, if you feel off balance emotionally, or out of sorts from a mental health standpoint, it can negatively effect your ability to keep a positive mindset towards these fundamental life issues, and that can create a downward spiral.</div>
<div>
<br></div>
<div>You might benefit from taking stock of your current financial situation, and seeking some objective input from a qualified financial advisor or retirement specialists, or at the minimum seeking out information and resources on managing your cash flow, living within your means, saving and investing.&nbsp;</div>
<div>
<br></div>
<div>Our core relationship with money itself is often at the root of feelings of uncertainty regarding issues like the fear of someday being homeless, of not having enough food to eat, or not being able to keep ourselves and our loved ones safe.</div>`;
pieletData.LBU = `
<p>Your relationships aren’t as deep and fulfilling as they could be, and (hard as it may be to hear) you’re likely at the root of any deficit you might be feeling regarding love and belonging.</p>
<p>Shallow or negative social interactions, unhealthy friendships, and poor relationships with our family are often the result of a lack of compassion for ourselves - from ourselves.&nbsp; If we don’t show ourselves compassion; if we can’t be intimate with ourselves; if we can’t drop our defenses and engage in play and truly enjoy our own company how can we expect to show up authentically and have more meaningful relationships with our family, friends, and community?</p>
<p>Moreover, if we aren’t intimate with ourselves, and showing ourselves and our friends, families and communities our compassion,&nbsp; our passion, and our natural unadulterated playful spirit, then what signals are we putting out to the world - and thus what types of people are we attracting?&nbsp;</p>
<p>People are like magnets for similarly minded people, and we tend to draw to us people who are similar to what we’re consciously or subconsciously putting out there.</p>
<p>You might consider taking an inventory of your relationships with your friends and family, and taking a look at the communities in which you’re involved.&nbsp; How are those people showing up?&nbsp; Are they negative?&nbsp; Positive?&nbsp; Compassionate? Cold and unfeeling?&nbsp; Do they show empathy and connectedness?&nbsp; Are their relationships deep or shallow?&nbsp; Are they okay being vulnerable and playful, or are they closed off?&nbsp; Are they authentic, or just operating with others at the level of pretense?&nbsp;</p>
<p>And how about you?&nbsp; Where can you improve these important areas of your life, and what might be possible for you with an increased opening for love and belonging?</p>
<p>You might consider working with a life coach, joining a faith-based community, or taking some self improvement courses.&nbsp; What you’ll find in any of those instances is a broader, deeper understanding, and acceptance of your self, which will in turn give you the opportunity to be naturally more connected to others.</p>`;
pieletData.ECU = `
<p>You may have some doubts about the value of the contributions you make, or have made in your life - to society, community, or even your family - and whether or not people respect what you’ve accomplished.&nbsp; It’s natural to measure ourselves against the expectations of others, but more importantly is how do measure ourselves against our own expectations of ourselves.&nbsp; And by what barometer?</p> 
<p>Most people would say that they have a good amount of self respect, but many people often report that they don’t know if their life has purpose - and if so, what that purpose is.&nbsp; Without a defined purpose, it’s hard to measure what our contributions have or have not been; what they are - or what they could be? And though we might like to think of our self esteem as existing in a vacuum - either we have it, or we don’t - it’s often relative. Relative to our expectations or ourselves, to others expectations of us, and most importantly to our spoken or unspoken sense of purpose.</p> 
<p>It’s worthwhile to consider your purpose in life, to begin having that conversation with yourself, and with your friends and family - and in your social circles.&nbsp; You don’t have to have “the answer” in order to start sharing that inner monologue in your dialogue with other.&nbsp; It will come.&nbsp;</p> 
<p>What matters is that in you’re in a powerful conversation about a purpose-driven life, and from there you can better gauge for yourself whether you’ve made the contributions that you want to make in this world, and whether you’ve been properly recognized for them - and if that even matters to you.&nbsp; To some it doesn't.</p> 
<p>Living from a declarative purpose, nagging questions of self worth, personal empowerment, inner strength, and self expression tend to naturally give way to the power of your purpose.</p>`;
pieletData.SAU = `<p>Self Actualization is a process - not a result.</p> 
<p>We are never completely self actualized, though hopefully we are continually self actualizing.&nbsp; All of us are just a work in progress.&nbsp; The quintessential question is are we actively working on it?&nbsp; Am I actively working on me?.&nbsp;</p> 
<p>The answer is&nbsp;“yes”.&nbsp; You are working on it - right now, in fact.&nbsp; You’re working on you - and that’s a good thing.&nbsp; It’s our nature as humans to seek to improve our lot in life, and our life itself.&nbsp;</p> 
<p>Self actualizing people are people who actively engage in this process of&nbsp;“self-improvement” by focusing first on the Self itself; by focusing on their&nbsp;“Being” - and on being the best human being they are capable of being, as fundamental to their well being.</p> 
<p>You might feel inadequate in this regard.&nbsp; Many people do.</p> 
<p>Self actualization looks like a long, steep road of self improvement, where you have to constantly "fix" yourself - but you should consider that choosing to consciously improve your Self does not mean that you’re broken.&nbsp; You are not broken - and you don’t need to be&nbsp;“fixed”.&nbsp;</p> 
<p>You are fundamentally good, and no matter what your state or situation - you can improve your Self itself, and other areas of your life will follow suit: your self esteem, your ability to be a contributor in life, your relationships and sense of belonging, your feelings of safety and security, and your physiological balance.</p> 
<p>“Self Actualization” isn’t a result of having gained some level of achievement in the other fundamental areas of your life.&nbsp; The work of continually self actualizing, is a propellent towards further improvement in all of those areas of life.</p> 
<p>Learning and living your purpose in life, seeking education in all of its forms towards practicing the mastery of new skills and achieving the goals that support your purpose to the point where you feel genuinely fulfilled, and capable of imbuing the possibility of that level of fulfillment to others - today, tomorrow, and the next day, until your short time on this Earth has passed.&nbsp; That’s a self actualizing life - and you’re living it.&nbsp;</p> 
<p>Keep living it.&nbsp; Keep sharing it.</p>`;
